# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0002_auto_20171214_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='order_service.Order')),
            ],
            options={
                'verbose_name': 'Order course',
                'verbose_name_plural': 'Order courses',
            },
        ),
    ]
