# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0004_auto_20171215_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
